version: '3'

services:
  account-service-database:
    image: ghcr.io/helpet-app/account-service-database:0.0.1-snapshot
    container_name: account-service-database
    ports:
      - '5432:5432'
    env_file:
      - .account-service-database.env
    volumes:
      - account-service-database-data:/var/lib/postgresql/data/
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - '6379:6379'
    entrypoint: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD --appendonly yes"
    env_file:
      - .redis.env
    volumes:
      - redis-data:/var/lib/redis/data/

volumes:
  account-service-database-data:
    driver: local
  redis-data:
    driver: local